 version: 0.0
 os: linux
 files: 
   - source: https://github.com/ManpraXSoftware/edx-platform/tree/Subodha/juniper.allfiles
     destination: /home/ubuntu/edx/pipeline
 hooks:
    BeforeInstall:
      - location: /install_dependencies
        timeout: 300
        runas: root
      - location: /start_server
        timeout: 300
        runas: root 
        
    AfterInstall:
       - location: /start.sh
         runas: root
         timeout: 300
        
